name: psy_ai_mobile_ready
description: "PsyAI - Thérapeute vocal IA (version mobile)"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  speech_to_text: ^7.0.0
  http: ^0.13.6
  flutter_tts: ^3.6.3
  just_audio: ^0.9.34
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
